sudo: false

addons:
  apt:
    packages:
    - graphviz

language: c
compiler:
  - gcc
  - clang

install:
  - ./get-deps.sh
  - ./build-deps.sh
script:
  - make -e all
  - make -e check

notifications:
  email: false