sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - graphviz

language: c
compiler:
  - gcc
  - clang

before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        brew update;
        brew install graphviz;
    fi
  - bison --version
  - flex --version

install:
  - ./get-deps.sh
  - ./get-extra-deps.sh
  - ./build-deps.sh
script:
  - make -e all
  - VERBOSE=1 make -e check

notifications:
  email: false